!function(n){var e={};function t(r){if(e[r])return e[r].exports;var o=e[r]={i:r,l:!1,exports:{}};return n[r].call(o.exports,o,o.exports,t),o.l=!0,o.exports}t.m=n,t.c=e,t.d=function(n,e,r){t.o(n,e)||Object.defineProperty(n,e,{enumerable:!0,get:r})},t.r=function(n){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(n,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(n,"__esModule",{value:!0})},t.t=function(n,e){if(1&e&&(n=t(n)),8&e)return n;if(4&e&&"object"==typeof n&&n&&n.__esModule)return n;var r=Object.create(null);if(t.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:n}),2&e&&"string"!=typeof n)for(var o in n)t.d(r,o,function(e){return n[e]}.bind(null,o));return r},t.n=function(n){var e=n&&n.__esModule?function(){return n.default}:function(){return n};return t.d(e,"a",e),e},t.o=function(n,e){return Object.prototype.hasOwnProperty.call(n,e)},t.p="",t(t.s="./src/js/main.js")}({"./src/js/_vars.js":
/*!*************************!*\
  !*** ./src/js/_vars.js ***!
  \*************************/
/*! exports provided: default */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony default export */ __webpack_exports__["default"] = ({\n  $window: window,\n  $document: document,\n  $html: document.documentElement,\n  $body: document.body\n});\n\n//# sourceURL=webpack:///./src/js/_vars.js?')},"./src/js/functions/accordion.js":
/*!***************************************!*\
  !*** ./src/js/functions/accordion.js ***!
  \***************************************/
/*! no static exports found */function(module,exports){eval("// accordion\nfunction accordions(accordionsSelector, contentSelector, controlSelector, activeClass) {\n  var accordions = document.querySelectorAll(accordionsSelector);\n  accordions.forEach(function (el) {\n    el.addEventListener('click', function (_ref) {\n      var currentTarget = _ref.currentTarget,\n          target = _ref.target;\n      var currentContent = currentTarget.querySelector(contentSelector),\n          currentController = currentTarget.querySelector(controlSelector);\n\n      if (target == currentController) {\n        var hide = function hide(parent, content, controller) {\n          parent.classList.remove(activeClass);\n          content.style.maxHeight = '';\n          controller.setAttribute('aria-expanded', false);\n          content.setAttribute('aria-hidden', true);\n        };\n\n        if (el.classList.contains(activeClass)) {\n          hide(currentTarget, currentContent, currentController);\n        } else {\n          accordions.forEach(function (item) {\n            var content = item.querySelector(contentSelector),\n                controller = item.querySelector(controlSelector);\n            hide(item, content, controller);\n          });\n          currentTarget.classList.add(activeClass);\n          currentContent.style.maxHeight = currentContent.scrollHeight + 'px';\n          currentController.setAttribute('aria-expanded', true);\n          currentContent.setAttribute('aria-hidden', false);\n        }\n      }\n    });\n  });\n}\n\naccordions('.accordion__item', '.accordion__content', '.accordion__control', 'open'); // accordion end\n\n//# sourceURL=webpack:///./src/js/functions/accordion.js?")},"./src/js/functions/animationOnScroll.js":
/*!***********************************************!*\
  !*** ./src/js/functions/animationOnScroll.js ***!
  \***********************************************/
/*! no static exports found */function(module,exports){eval("// function animation with css animate //\n// add class .animate__animated and attribute data-animation-name=\"\" on element //\nfunction animationOnScroll(animElements, dataArrtibute, activeClass, noHideClass) {\n  var animItems = document.querySelectorAll(animElements);\n\n  if (animItems.length > 0) {\n    var offset = function offset(el) {\n      var rect = el.getBoundingClientRect().top,\n          scrollTop = window.pageYOffset || document.documentElement.scrollTop;\n      return rect + scrollTop;\n    };\n\n    window.addEventListener('scroll', function () {\n      animItems.forEach(function (item) {\n        var itemHeight = item.offsetHeight,\n            itemOffset = offset(item),\n            animStart = 4,\n            animationName = item.getAttribute(dataArrtibute) || activeClass;\n        var itemPoint = window.innerHeight - itemHeight / animStart;\n\n        if (itemHeight > window.innerHeight) {\n          itemPoint = window.innerHeight - window.innerHeight / animStart;\n        }\n\n        if (window.pageYOffset > itemOffset - itemPoint && window.pageYOffset < itemOffset + itemHeight) {\n          item.classList.add(animationName);\n        } else {\n          if (!item.classList.contains(noHideClass)) {\n            item.classList.remove(animationName);\n          }\n        }\n      });\n    });\n  }\n}\n\nanimationOnScroll('.animate__animated', 'data-animation-name', 'animate_active', 'anim-no-hide');\n\n//# sourceURL=webpack:///./src/js/functions/animationOnScroll.js?")},"./src/js/functions/tabs.js":
/*!**********************************!*\
  !*** ./src/js/functions/tabs.js ***!
  \**********************************/
/*! no static exports found */function(module,exports){eval("// tabs\nvar tabsContainer = document.querySelector('.tabs__navigation');\nvar tabs = document.querySelectorAll('.tabs__btn');\nvar tabsContent = document.querySelectorAll('.tabs__content');\n\nfunction hideTabs() {\n  tabsContent.forEach(function (item) {\n    item.classList.remove('show');\n    item.setAttribute('aria-hidden', true);\n  });\n  tabs.forEach(function (tab) {\n    tab.classList.remove('active');\n    tab.setAttribute('aria-expanded', false);\n  });\n}\n\nfunction showTabs() {\n  var i = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : 0;\n  tabsContent[i].classList.add('show');\n  tabsContent[i].setAttribute('aria-hidden', false);\n  tabs[i].classList.add('active');\n  tabs[i].setAttribute('aria-expanded', true);\n}\n\nhideTabs();\nshowTabs();\ntabsContainer.addEventListener('click', function (_ref) {\n  var target = _ref.target;\n\n  if (target.classList.contains('tabs__btn')) {\n    tabs.forEach(function (item, i) {\n      if (target == item) {\n        hideTabs();\n        showTabs(i);\n      }\n    });\n  }\n}); // tabs end\n\n//# sourceURL=webpack:///./src/js/functions/tabs.js?")},"./src/js/functions/webp.js":
/*!**********************************!*\
  !*** ./src/js/functions/webp.js ***!
  \**********************************/
/*! no static exports found */function(module,exports){eval('function testWebP(callback) {\n  var webP = new Image();\n\n  webP.onload = webP.onerror = function () {\n    callback(webP.height == 2);\n  };\n\n  webP.src = "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACyAgCdASoCAAIALmk0mk0iIiIiIgBoSygABc6WWgAA/veff/0PP8bA//LwYAAA";\n}\n\ntestWebP(function (support) {\n  if (support == true) {\n    document.querySelector("body").classList.add("webp");\n  } else {\n    document.querySelector("body").classList.add("no-webp");\n  }\n});\n\n//# sourceURL=webpack:///./src/js/functions/webp.js?')},"./src/js/main.js":
/*!************************!*\
  !*** ./src/js/main.js ***!
  \************************/
/*! no exports provided */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _vars__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./_vars */ "./src/js/_vars.js");\n/* harmony import */ var _functions_webp__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./functions/webp */ "./src/js/functions/webp.js");\n/* harmony import */ var _functions_webp__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(_functions_webp__WEBPACK_IMPORTED_MODULE_1__);\n/* harmony import */ var _functions_accordion_js__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./functions/accordion.js */ "./src/js/functions/accordion.js");\n/* harmony import */ var _functions_accordion_js__WEBPACK_IMPORTED_MODULE_2___default = /*#__PURE__*/__webpack_require__.n(_functions_accordion_js__WEBPACK_IMPORTED_MODULE_2__);\n/* harmony import */ var _functions_animationOnScroll__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ./functions/animationOnScroll */ "./src/js/functions/animationOnScroll.js");\n/* harmony import */ var _functions_animationOnScroll__WEBPACK_IMPORTED_MODULE_3___default = /*#__PURE__*/__webpack_require__.n(_functions_animationOnScroll__WEBPACK_IMPORTED_MODULE_3__);\n/* harmony import */ var _functions_tabs__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ./functions/tabs */ "./src/js/functions/tabs.js");\n/* harmony import */ var _functions_tabs__WEBPACK_IMPORTED_MODULE_4___default = /*#__PURE__*/__webpack_require__.n(_functions_tabs__WEBPACK_IMPORTED_MODULE_4__);\n\n\n\n\n\n\n//# sourceURL=webpack:///./src/js/main.js?')}});
//# sourceMappingURL=main.js.map
